name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14'
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm t
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
