name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (for GitGuardian)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install GitGuardian CLI
        run: pip install ggshield
      - name: Run GitGuardian scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan repo .
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14'
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm t
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Docker
        run: npm run docker:build
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
